# -*- coding: utf-8 -*-
"""Lead_lag_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SiZ5EvFrvNpfyygr7tmCm7jfwaAjeVM

# Загрузка данных, расчет доходностей
Источники:

В статье
  - https://www.crsp.org/research/crsp-us-stock-databases/ (можно попробовать сделать запрос для получения данных)
  - https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html s include the market return (MKT), size (SMB), value (HML), profitability (RMW), investment (CMA), and momentumn (MOM)  (пока не понял зачем, возмонжно, для портфолио, использование CAPM

Начнем со скачивания данных с yahoofinance
"""

# !pip install yfinance -q
import yfinance as yf
import bs4 as bs
import numpy as np
import pandas as pd
import scipy.stats as stats
import os
import requests
from datetime import datetime
from pandas.core.frame import DataFrame
import matplotlib.pyplot as plt
import networkx as nx
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px
from collections import defaultdict

"""$$r_{i,t}^{close-to-close} = P_{i,t}^{Adj close}/P_{i,t-1}^{Adj close} -1$$
$$r_{i,t}^{daytime} = P_{i,t}^{close}/P_{i,t}^{open} -1$$
$$r_{i,t}^{overnight} = (1+ r_{i,t}^{close-to-close})/(1+r_{i,t}^{daytime}) -1$$

$$ρ_{i, j}^{overnight-lead-daytime} = Pearson.corr(r_{i,t}^{overnight}, r_{j,t}^{daytime})$$

$$ρ_{i, j}^{daytime-lead-overnight} = Pearson.corr(r_{i,t-1}^{daytime}, r_{j,t}^{overnight})$$

"""

scrape_data = False # Чтобы не грузить данные каждый раз. False - загрузить данные с диска, True - собрать данные снова

def download_prices(tickers, start_date, end_date):
    # Загружаем все данные сразу
    data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=False)

    returns_data = {}

    for ticker in tickers:
      df = pd.DataFrame({
          'close': data['Close'][ticker],
          'open': data['Open'][ticker],
          'adj_close': data['Adj Close'][ticker]
      }).dropna()

      # Расчет доходностей
      df['close_to_close'] = df['adj_close'] / df['adj_close'].shift(1) - 1
      df['daytime'] = df['close'] / df['open'] - 1
      df['overnight'] = (1 + df['close_to_close']) / (1 + df['daytime']) - 1

      df['ticker'] = ticker
      returns_data[ticker] = df[['close_to_close', 'daytime', 'overnight', 'ticker']]

    # Объединяем все данные
    all_returns = pd.concat(returns_data.values())
    return all_returns.reset_index().rename(columns={'index': 'date'})

if scrape_data:
  # названия тикеров с сайта
  resp = requests.get('https://stockanalysis.com/list/sp-500-stocks/')

  soup = bs.BeautifulSoup(resp.text, 'lxml')
  table = soup.find('table')
  tickers = []
  for row in table.findAll('tr')[1:]:
      ticker = row.findAll('td')[1].text
      industry = row.findAll('td')[1].text
      tickers.append(ticker)
  tickers = [s.replace('\n', '') for s in tickers]

  # sector
  df_sectors = pd.read_csv('/content/tickers.txt', sep='\t').rename(columns = {'Symbol': 'ticker'})
  df_sectors = df_sectors[['ticker', 'Industry', 'Sector']]
  returns_df = download_prices(tickers, '2020-01-01', '2024-12-31')
  returns_df = returns_df.merge(df_sectors, how = 'left', on = 'ticker')

  returns_df.to_parquet('/content/drive/MyDrive/Диплом_магистртура/data.parquet')
else:
  returns_df = pd.read_parquet('/content/drive/MyDrive/Диплом_магистртура/data.parquet', engine='pyarrow')

"""# Матрицы корреляций

"""

# Функция для расчета матриц корреляции
def calculate_correlations(data, tickers, lookback_days=60):
    data = data.copy()
    data['Date'] = pd.to_datetime(data['Date'])

    # Берем последние lookback_days дней
    all_dates = sorted(data['Date'].unique())
    end_date = all_dates[-1]
    start_date = all_dates[-lookback_days]

    window_data = data[(data['Date'] >= start_date) & (data['Date'] <= end_date)]

    n = len(tickers)
    corr_overnight_daytime = np.full((n, n), np.nan)
    corr_daytime_overnight = np.full((n, n), np.nan)

    overnight_pivot = window_data.pivot(index='Date', columns='ticker', values='overnight')
    daytime_pivot = window_data.pivot(index='Date', columns='ticker', values='daytime')

    for i in range(n):
        for j in range(n):
            ticker_i = tickers[i]
            ticker_j = tickers[j]

            # 1. Overnight_i -> Daytime_j
            df_ol_dt = pd.DataFrame({
                'overnight': overnight_pivot[ticker_i],
                'daytime': daytime_pivot[ticker_j]
            }).dropna()


            corr_ol_dt = stats.pearsonr(df_ol_dt['overnight'], df_ol_dt['daytime'])[0]
            corr_overnight_daytime[i,j] = corr_ol_dt

            # 2. Daytime_i -> Overnight_j (со сдвигом)
            df_dt_ol = pd.DataFrame({
                'daytime_shifted': daytime_pivot[ticker_i].shift(1),  # Сдвиг на 1 день
                'overnight': overnight_pivot[ticker_j]
            }).dropna()


            corr_dt_ol = stats.pearsonr(df_dt_ol['daytime_shifted'], df_dt_ol['overnight'])[0]
            corr_daytime_overnight[i,j] = corr_dt_ol

    return corr_overnight_daytime, corr_daytime_overnight

# Тест
tickers_subset = ['NVDA', 'AAPL', 'MSFT', 'GOOGL', 'AMZN']
corr_overnight_daytime, corr_daytime_overnight = calculate_correlations(returns_df, tickers_subset)

print("Overnight-Lead-Daytime:")
print(pd.DataFrame(corr_overnight_daytime, index=tickers_subset, columns=tickers_subset).round(4))

print("\nDaytime-Lead-Overnight:")
print(pd.DataFrame(corr_daytime_overnight, index=tickers_subset, columns=tickers_subset).round(4))

"""## Анализ корреляций

## T-test
"""

def test_correlation_significance(correlation, n_samples, alpha=0.05):
    """
    Тест значимости корреляции Пирсона

    H0: корреляция = 0 (нет связи)
    H1: корреляция ≠ 0 (есть связь)
    """

    t_stat = correlation * np.sqrt(n_samples - 2) / np.sqrt(1 - correlation**2)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_stat), df=n_samples-2))

    return p_value

def sector_correlations_t_test(returns_df, lookback_days=60, alpha=0.05, min_correlation=0.2):
    results = []

    sector_counts = returns_df['Sector'].unique()

    for sector in sector_counts:
        # Тикеры и данные сектора
        sector_tickers = returns_df[returns_df['Sector'] == sector]['ticker'].unique().tolist()
        sector_data = returns_df[returns_df['ticker'].isin(sector_tickers)]

        print(f"  {sector}: {len(sector_tickers)} акций")

        # Ваша функция
        corr_ol_dt, corr_dt_ol = calculate_correlations(sector_data, sector_tickers, lookback_days)

        # Только сильные корреляции
        for i in range(len(sector_tickers)):
            for j in range(len(sector_tickers)):
                if i != j:
                    # OL→DT
                    if not np.isnan(corr_ol_dt[i, j]) and abs(corr_ol_dt[i, j]) > min_correlation:
                        p_value = test_correlation_significance(corr_ol_dt[i, j], lookback_days)
                        if p_value < alpha:
                            results.append({
                                'sector': sector,
                                'i': sector_tickers[i],
                                'j': sector_tickers[j],
                                'corr': corr_ol_dt[i, j],
                                'p_value': p_value,
                                'type': 'overnight→daytime'
                            })

                if not np.isnan(corr_dt_ol[i, j]):
                    if abs(corr_dt_ol[i, j]) > min_correlation:
                        p_value = test_correlation_significance(corr_dt_ol[i, j], lookback_days)
                        if p_value < alpha:
                            results.append({
                                'sector': sector,
                                'i': sector_tickers[i],
                                'j': sector_tickers[j],
                                'corr': corr_dt_ol[i, j],
                                'p_value': p_value,
                                'type': 'daytime→overnight'
                            })

    return pd.DataFrame(results)

sector_results = sector_correlations_t_test(returns_df, lookback_days=60)

# sector_results.loc[sector_results['p_value'] < 0.05, 'significant'] = 'YES'
# sector_results.loc[sector_results['p_value'] > 0.05, 'significant'] = 'NO'
sector_results[sector_results['p_value'] > 0.05]
# sector_results.groupby(['type', 'sector', 'significant'])['correlation'].count()

"""## Bootstrap"""

def analyze_sectors_compact(returns_df, lookback_days=60, alpha=0.05,
                           n_bootstrap=200):


    results = []
    returns_df = returns_df.copy()

    sectors_to_analyze = returns_df['Sector'].unique()

    for sector in sectors_to_analyze:
        # Данные сектора
        sector_tickers = returns_df[returns_df['Sector'] == sector]['ticker'].unique().tolist()
        sector_data = returns_df[returns_df['ticker'].isin(sector_tickers)]

        print(f"\n{sector}: {len(sector_tickers)} акций")

        # Моя корреляция
        sector_data_dates = sector_data['Date'].unique()
        end_date = sorted(sector_data_dates)[-1]
        start_date = sorted(sector_data_dates)[-lookback_days]

        window = sector_data[
            (sector_data['Date'] >= start_date) &
            (sector_data['Date'] <= end_date)
        ]

        overnight = window.pivot(index='Date', columns='ticker', values='overnight')
        daytime = window.pivot(index='Date', columns='ticker', values='daytime')
        for i in range(len(sector_tickers)):
            for j in range(len(sector_tickers)):
              ticker_i = sector_tickers[i]
              ticker_j = sector_tickers[j]

              # OL→DT
              df_ol_dt = pd.DataFrame({
                  'ol': overnight[ticker_i],
                  'dt': daytime[ticker_j]
              }).dropna()

              if len(df_ol_dt) >= 20:
                  # # Bootstrap тест
                  # x = df_ol_dt['ol'].values
                  # y = df_ol_dt['dt'].values
                  # n = len(x)

                  # Наблюдаемая корреляция
                  corr_ol_dt = stats.pearsonr(df_ol_dt['ol'], df_ol_dt['dt'])[0]

                  # Bootstrap
                  bootstrap_corrs = []
                  for _ in range(n_bootstrap):
                      idx = np.random.permutation(len(df_ol_dt['ol']))
                      y_shuffled = df_ol_dt['dt'].values[idx]
                      corr = stats.spearmanr(df_ol_dt['ol'].values, y_shuffled)[0]
                      bootstrap_corrs.append(corr)

                  # p-value
                  p_value = np.mean(np.abs(bootstrap_corrs) >= np.abs(corr_ol_dt))


                  if p_value < alpha:
                      results.append({
                          'sector': sector,
                          'type': 'overnight→daytime',
                          'i': ticker_i,
                          'j': ticker_j,
                          'correlation_pearson': corr_ol_dt,
                          # 'correlation_spearman': observed_corr,
                          'p_value': p_value
                          # 'n_obs': n
                      })

              # DT→OL (со сдвигом)
              df_dt_ol = pd.DataFrame({
                  'dt': daytime[ticker_i].shift(1),
                  'ol': overnight[ticker_j]
              }).dropna()

              if len(df_ol_dt) >= 20:

                  # Наблюдаемая корреляция
                  corr_ol_dt = stats.pearsonr(df_ol_dt['ol'], df_ol_dt['dt'])[0]

                  # Bootstrap
                  bootstrap_corrs = []
                  for _ in range(n_bootstrap):
                      idx = np.random.permutation(len(df_ol_dt['ol']))
                      y_shuffled = df_ol_dt['dt'].values[idx]
                      corr = stats.spearmanr(df_ol_dt['ol'].values, y_shuffled)[0]
                      bootstrap_corrs.append(corr)

                  # p-value
                  p_value = np.mean(np.abs(bootstrap_corrs) >= np.abs(corr_ol_dt))


                  if p_value < alpha:
                      results.append({
                          'sector': sector,
                          'type': 'overnight→daytime',
                          'i': ticker_i,
                          'j': ticker_j,
                          'correlation_pearson': corr_ol_dt,
                          # 'correlation_spearman': observed_corr,
                          'p_value': p_value
                          # 'n_obs': n
                      })
    df_results = pd.DataFrame(results)


    return df_results

results = analyze_sectors_compact(
    returns_df,
    lookback_days=60,              # 60 дней
    alpha=0.05,                    # 5% уровень значимости
    n_bootstrap=200               # 200 итераций bootstrap
)

results.to_csv('bootstrap_result.csv')







"""# Анализ старая версия"""

class LeadLagAnalyzer:
    def __init__(self, corr_ol_dt, corr_dt_ol, tickers):
        self.corr_ol_dt = corr_ol_dt
        self.corr_dt_ol = corr_dt_ol
        self.tickers = tickers

    def analyze_all(self, edge_threshold=0.1):
        """Полный анализ аналогичный Streamlit дашборду"""
        print("LEAD-LAG ANALYSIS ===\n")

        # 1. Heatmaps
        self.plot_heatmaps()

        # 2. Network Analysis
        self.analyze_networks(edge_threshold)

        # 3. Lead-Lag Patterns
        self.analyze_patterns()

        # 4. Detailed Statistics
        self.print_detailed_stats()

    def plot_heatmaps(self):
        """Тепловые карты корреляций"""
        print("HEATMAPS")

        fig = make_subplots(
            rows=1, cols=2,
            subplot_titles=("Overnight-Lead-Daytime", "Daytime-Lead-Overnight")
        )

        # Heatmap 1: Overnight-Lead-Daytime
        fig.add_trace(
            go.Heatmap(
                z=self.corr_ol_dt,
                x=self.tickers,
                y=self.tickers,
                colorscale='RdBu_r',
                zmid=0
            ),
            row=1, col=1
        )

        # Heatmap 2: Daytime-Lead-Overnight
        fig.add_trace(
            go.Heatmap(
                z=self.corr_dt_ol,
                x=self.tickers,
                y=self.tickers,
                colorscale='RdBu_r',
                zmid=0
            ),
            row=1, col=2
        )

        fig.update_layout(height=500, title_text="Correlation Matrices")
        fig.show()

        # Статистика по матрицам
        self._print_matrix_stats()

    def _print_matrix_stats(self):
        """Статистика корреляционных матриц"""
        ol_nonzero = self.corr_ol_dt[self.corr_ol_dt != 0]
        dt_nonzero = self.corr_dt_ol[self.corr_dt_ol != 0]

        print(f"\n MATRIX STATISTICS:")
        print(f"Overnight-Lead-Daytime:")
        print(f"  Mean: {np.mean(ol_nonzero):.4f}")
        print(f"  Max:  {np.max(self.corr_ol_dt):.4f}")
        print(f"  Min:  {np.min(self.corr_ol_dt):.4f}")
        print(f"  Std:  {np.std(ol_nonzero):.4f}")

        print(f"Daytime-Lead-Overnight:")
        print(f"  Mean: {np.mean(dt_nonzero):.4f}")
        print(f"  Max:  {np.max(self.corr_dt_ol):.4f}")
        print(f"  Min:  {np.min(self.corr_dt_ol):.4f}")
        print(f"  Std:  {np.std(dt_nonzero):.4f}")

    def analyze_networks(self, threshold=0.1):
        """Анализ сетей"""
        print(f"\n NETWORK ANALYSIS (threshold: {threshold})")

        # Анализ обеих сетей
        for matrix_type, matrix in [("Overnight-Lead-Daytime", self.corr_ol_dt),
                                   ("Daytime-Lead-Overnight", self.corr_dt_ol)]:
            print(f"\n--- {matrix_type} ---")
            G = self._build_network(matrix, threshold)

            if G.number_of_edges() > 0:
                self._plot_network(G, matrix_type)
                self._print_network_stats(G, matrix_type)
            else:
                print("  No significant edges found")

    def _build_network(self, correlation_matrix, threshold):
        """Построение направленного графа"""
        G = nx.DiGraph()

        # Добавляем узлы
        for ticker in self.tickers:
            G.add_node(ticker)

        # Добавляем ребра
        for i in range(len(self.tickers)):
            for j in range(len(self.tickers)):
                if i != j and abs(correlation_matrix[i, j]) > threshold:
                    G.add_edge(self.tickers[i], self.tickers[j],
                              weight=correlation_matrix[i, j])

        return G

    def _plot_network(self, G, title):
        """Визуализация сети"""
        plt.figure(figsize=(12, 8))

        # Позиционирование узлов
        pos = nx.spring_layout(G, k=2, iterations=50)

        # Размер узлов по исходящей степени
        out_degree = dict(G.out_degree())
        node_sizes = [300 + out_degree[node] * 100 for node in G.nodes()]

        # Цвет узлов по исходящей степени
        node_colors = list(out_degree.values())

        # Рисуем ребра
        edge_colors = ['red' if G[u][v]['weight'] < 0 else 'green'
                      for u, v in G.edges()]
        edge_widths = [abs(G[u][v]['weight']) * 3 for u, v in G.edges()]

        nx.draw_networkx_edges(G, pos, edge_color=edge_colors,
                              width=edge_widths, alpha=0.6,
                              arrows=True, arrowsize=20)

        # Рисуем узлы
        nodes = nx.draw_networkx_nodes(G, pos, node_size=node_sizes,
                                     node_color=node_colors,
                                     cmap='viridis', alpha=0.8)

        # Подписи
        nx.draw_networkx_labels(G, pos, font_size=8)

        plt.colorbar(nodes, label='Out-degree (Leadership)')
        plt.title(f'{title} Network')
        plt.axis('off')
        plt.tight_layout()
        plt.show()

    def _print_network_stats(self, G, network_type):
        """Статистика сети"""
        out_degrees = dict(G.out_degree())
        in_degrees = dict(G.in_degree())

        print(f"  Nodes: {G.number_of_nodes()}")
        print(f"  Edges: {G.number_of_edges()}")
        print(f"  Density: {nx.density(G):.4f}")

        # Топ лидеры
        top_leaders = sorted(out_degrees.items(), key=lambda x: x[1], reverse=True)[:5]
        print(f"  Top Leaders: {[f'{ticker}({deg})' for ticker, deg in top_leaders]}")

        # Топ лагеры
        top_laggers = sorted(in_degrees.items(), key=lambda x: x[1], reverse=True)[:5]
        print(f"  Top Laggers: {[f'{ticker}({deg})' for ticker, deg in top_laggers]}")

    def analyze_patterns(self):
        """Анализ паттернов lead-lag"""
        print(f"\n📈 LEAD-LAG PATTERNS")

        # Распределения корреляций
        ol_corrs = self.corr_ol_dt[self.corr_ol_dt != 0].flatten()
        dt_corrs = self.corr_dt_ol[self.corr_dt_ol != 0].flatten()

        fig = make_subplots(rows=1, cols=2, subplot_titles=[
            "Overnight-Lead-Daytime", "Daytime-Lead-Overnight"
        ])

        fig.add_trace(go.Histogram(x=ol_corrs, name="OL→DT", nbinsx=30), row=1, col=1)
        fig.add_trace(go.Histogram(x=dt_corrs, name="DT→OL", nbinsx=30), row=1, col=2)

        fig.update_layout(height=400, title_text="Correlation Distributions")
        fig.show()

        # Асимметрия
        self._print_asymmetry_analysis(ol_corrs, dt_corrs)

    def _print_asymmetry_analysis(self, ol_corrs, dt_corrs):
        """Анализ асимметрии"""
        ol_mean = np.mean(np.abs(ol_corrs))
        dt_mean = np.mean(np.abs(dt_corrs))

        ol_positive = np.sum(ol_corrs > 0)
        ol_negative = np.sum(ol_corrs < 0)
        dt_positive = np.sum(dt_corrs > 0)
        dt_negative = np.sum(dt_corrs < 0)

        print(f"\n ASYMMETRY ANALYSIS:")
        print(f"Overnight-Lead-Daytime:")
        print(f"  Avg |correlation|: {ol_mean:.4f}")
        print(f"  Positive/Negative: {ol_positive}/{ol_negative}")

        print(f"Daytime-Lead-Overnight:")
        print(f"  Avg |correlation|: {dt_mean:.4f}")
        print(f"  Positive/Negative: {dt_positive}/{dt_negative}")

        if ol_mean > dt_mean:
            print(" TUG-OF-WAR EVIDENCE: Overnight-lead relationships are stronger!")
        else:
            print("ℹ Daytime-lead relationships are stronger")

    def print_detailed_stats(self):
        """Детальная статистика"""
        print(f"\n DETAILED STATISTICS")

        # Самые сильные связи
        print(" STRONGEST LEAD-LAG RELATIONSHIPS:")

        for matrix_type, matrix in [("OL→DT", self.corr_ol_dt),
                                   ("DT→OL", self.corr_dt_ol)]:
            print(f"\n{matrix_type}:")
            strong_pairs = []

            for i in range(len(self.tickers)):
                for j in range(len(self.tickers)):
                    if i != j and not np.isnan(matrix[i, j]):
                        strong_pairs.append((self.tickers[i], self.tickers[j], matrix[i, j]))

            # Топ 5 самых сильных связей
            top_pairs = sorted(strong_pairs, key=lambda x: abs(x[2]), reverse=True)[:5]
            for leader, lagger, corr in top_pairs:
                direction = "↑↑" if corr > 0 else "↑↓"
                print(f"  {leader} → {lagger}: {corr:.4f} {direction}")

    def analyze_stock_pair(self, stock1, stock2):
        """Анализ конкретной пары акций"""
        if stock1 not in self.tickers or stock2 not in self.tickers:
            print("Stocks not found in ticker list")
            return

        idx1 = self.tickers.index(stock1)
        idx2 = self.tickers.index(stock2)

        ol_dt_corr = self.corr_ol_dt[idx1, idx2]
        dt_ol_corr = self.corr_dt_ol[idx1, idx2]

        print(f"\n PAIR ANALYSIS: {stock1} vs {stock2}")
        print(f"Overnight {stock1} → Daytime {stock2}: {ol_dt_corr:.4f}")
        print(f"Daytime {stock1} → Overnight {stock2}: {dt_ol_corr:.4f}")

        # Интерпретация
        if abs(ol_dt_corr) > 0.2:
            direction = "positive" if ol_dt_corr > 0 else "negative"
            print(f" Strong {direction} lead-lag relationship detected!")

# ИСПОЛЬЗОВАНИЕ
print("=== LEAD-LAG ANALYSIS STARTING ===")

corr_overnight_daytime, corr_daytime_overnight = calculate_correlations(returns_df, tickers)

# Создаем анализатор
analyzer = LeadLagAnalyzer(corr_overnight_daytime, corr_daytime_overnight, tickers)

analyzer.analyze_all(edge_threshold=0.1)

# # Анализ конкретных пар
# analyzer.analyze_stock_pair('NVDA', 'AAPL')
# analyzer.analyze_stock_pair('MSFT', 'GOOGL')

"""Heatmap не знаю какие выводы

По  _print_matrix_stats Асимметрия направлений:
 - Overnight→Daytime: -0.0096 (отрицательное)
 - Daytime→Overnight: +0.0034 (положительное)

NETWORK ANALYSIS
  - плотность 50%
  - можем выбрать более высокий порог, 0.1 мало
  - Overnight-Lead-Daytime: если JBL сильный рост ночью, то днем рост TRMB

ночные возвраты действительно являются более сильными лидерами:
OL→DT: 0.1212 vs DT→OL: 0.1071, что соответствует выводам статьи о "информационном преимуществе" ночных периодов

Сетевая структура - обнаружены четкие lead-lag паттерны между разными акциями:
Сильные связи типа WFC → TRMB (0.8126)

"""
